version: '3.5'

services:
  app:
    container_name: ${SERVICE_NAME}-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./app/:/usr/src/app/
      - ./.env/:/usr/src/app/.env
    expose:
      - "80"
    networks:
      traefik: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=PathPrefix(`/${SERVICE_NAME}`)"

networks:
  traefik:
    external: true
    name: traefik_default